### PR TITLE
Delete FluentPVCBinding if it times out without becoming Ready condition

### LINKED ISSUE #38: FluentPVCBinding remains as Unknown status
### Description

Sometimes, the resources created by fluent-pvc-operator remains even when there is no target pod.

Here are the conditions of each resources:

FluentPVCBinding
* The status is `Unknown`.
* The managed pod’s name is empty.

PVC
* The status is `Pending`.
* It waits for utilization by the pod after displaying `WaitForFirstConsumer` events.

This seems to occur when the deployment is updated.

### Expected behavior

Since the target pod name is empty, it meets the following conditions for the `fluentpvcbinding_controller.go`, resulting in `Unknown` status after one hour.

https://github.com/st-tech/fluent-pvc-operator/blob/70dcd1589b2436ae2ec26f82f430ba8411a51918/controllers/fluentpvcbinding_controller.go#L109-L113

Given that the target pod name is empty, the target pod definitely does not exist. Therefore, unnecessary FluentPVCBinding and PVC should be removed.

### [Kubernetes](https://kubernetes.io/releases/) version

1.20.7

### [cert-manager](https://github.com/jetstack/cert-manager/releases) version

1.3.1

### [fluent-pvc-operator](https://github.com/st-tech/fluent-pvc-operator/releases) version

0.0.4

### What kind of Kubernetes?

Amazon Elastic Kubernetes Service

### How to Reproduce

As a reproduction method, we can create a situation where the pod webhook times out after [10 seconds](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#:~:text=Default%20timeout%20for%20a%20webhook%20call%20is%2010%20seconds%2C%20You%20can%20set%20the%20timeout%20and%20it%20is%20encouraged%20to%20use%20a%20short%20timeout%20for%20webhooks.%20If%20the%20webhook%20call%20times%20out%2C%20the%20request%20is%20handled%20according%20to%20the%20webhook%27s%20failure%20policy.
), so we intentionally wait for 11 seconds within the webhook processing.

FluentPVCBinding and PVC will be created, but the pod will not be created.
The pod name is not empty, but the situation described above can be reproduced.

I have prepared a branch with the applied reproduction method, so please check it here.
* https://github.com/R-HNF/fluent-pvc-operator/tree/reproduce-issue38

In addition, I have also made modifications to ensure compatibility with Apple Silicon (arm chip) in the branch. If you're curious about the changes for Apple Silicon, please try the reproduction method on an AMD-based PC.

### Output

Here are a screenshot and descriptions when reproducing it locally.

image

<details><summary>FluentPVCBinding description</summary>
<p>

```
Name:         example-fluent-pvc-binding-6cfc78f455-5bb895cfdc
Namespace:    example-ns
Labels:       <none>
Annotations:  <none>
API Version:  fluent-pvc-operator.tech.zozo.com/v1alpha1
Kind:         FluentPVCBinding
Metadata:
  Creation Timestamp:  2024-06-19T11:19:42Z
  Finalizers:
    fluent-pvc-operator.tech.zozo.com/fluentpvcbinding-protection
  Generation:  1
  Managed Fields:
    API Version:  fluent-pvc-operator.tech.zozo.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"fluent-pvc-operator.tech.zozo.com/fluentpvcbinding-protection":
        f:ownerReferences:
          .:
          k:{"uid":"fe34dc8a-9d35-467b-b86f-b4ad94246d6a"}:
      f:spec:
        .:
        f:fluentPVC:
          .:
          f:name:
          f:uid:
        f:pod:
          .:
          f:name:
          f:uid:
        f:pvc:
          .:
          f:name:
          f:uid:
    Manager:      manager
    Operation:    Update
    Time:         2024-06-19T11:19:42Z
    API Version:  fluent-pvc-operator.tech.zozo.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
          .:
          k:{"type":"Unknown"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
        f:phase:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2024-06-19T12:19:42Z
  Owner References:
    API Version:           fluent-pvc-operator.tech.zozo.com/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  FluentPVC
    Name:                  example-fluent-pvc
    UID:                   fe34dc8a-9d35-467b-b86f-b4ad94246d6a
  Resource Version:        2982639884
  UID:                     f8669542-c668-4116-8127-da428bbfca96
Spec:
  Fluent PVC:
    Name:  example-fluent-pvc
    UID:   fe34dc8a-9d35-467b-b86f-b4ad94246d6a
  Pod:
    Name: 
    UID:  
  Pvc:
    Name:  example-pvc-6cfc78f455-5bb895cfdc
    UID:   bab98cc7-eabe-4271-89bc-f12c2badba5a
Status:
  Conditions:
    Last Transition Time:  2024-06-19T12:19:42Z
    Message:               Pod=''(UID='') is not found even though it hasn't been finalized since it became Ready status.(fluentpvcbinding='example-fluent-pvc-binding-6cfc78f455-5bb895cfdc')
    Reason:                PodNotFound
    Status:                True
    Type:                  Unknown
  Phase:                   Unknown
Events:                    <none>
```

</p>
</details> 

<details><summary>PVC description</summary>
<p>

```
Name:          example-pvc-6cfc78f455-5bb895cfdc
Namespace:     example-ns
StorageClass:  gp2
Status:        Pending
Volume:       
Labels:        <none>
Annotations:   <none>
Finalizers:    [fluent-pvc-operator.tech.zozo.com/pvc-protection kubernetes.io/pvc-protection]
Capacity:     
Access Modes: 
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type    Reason                Age                    From                         Message
  ----    ------                ----                   ----                         -------
  Normal  WaitForFirstConsumer  4s (x1481 over 6h10m)  persistentvolume-controller  waiting for first consumer to be created before binding
```

</p>
</details>

### PR DESCRIPTION
**Pull request by R-HNF**
## Which issue(s) this PR fixes:

Fixes #38 

## What this PR does / why we need it:

**Why**
If FluentPVCBinding cannot find the target pod within one hour, it remains in `Unknown` status as an unnecessary resource in Kubernetes cluster. Such unnecessary resources can potentially impact the cluster and operations adversely, so I will modify it to be deleted. I added a process to delete PVC for the same reason.

**Changes**
* Adding `PodMissing` condition.
* If FluentPVCBinding cannot find the Pod and the FluentPVCBinding does not become the Ready condition within one hour, instead of setting the it to `Unknown` status, it will be deleted.
* When PVC controller detects that FluentPVCBinding has become PodMissing, the PVC will proceed with deletion. Subsequently, FluentPVCBinding controller confirms that the PVC has disappeared and proceeds to delete the FluentPVCBinding.

## How test it:

I have prepared a branch with applied the fixes and the reproduction method, so please check it here.

* https://github.com/R-HNF/fluent-pvc-operator/tree/test-fix-issue38

In addition, I have also made modifications to ensure compatibility with Apple Silicon (arm chip) in the branch. If you're curious about the changes for Apple Silicon, please try the reproduction method on an AMD-based PC.

### CODE REVIEW

File: controllers/fluentpvcbinding_controller.go [hunk 1]
```diff
@@ -108,7 +116,7 @@ func (r *fluentPVCBindingReconciler) Reconcile(ctx context.Context, req ctrl.Req
 
 	if !podFound && !b.IsConditionReady() {
```
Comment (banatt) [inline controllers/fluentpvcbinding_controller.go:117]: FYI
`Ready` condition is false only until both pod and pvc are found.
https://github.com/st-tech/fluent-pvc-operator/blob/70dcd1589b2436ae2ec26f82f430ba8411a51918/controllers/fluentpvcbinding_controller.go#L151-L153

And, `SetConditionNotReady` is not used in this repository, so the `Ready` condition will never revert to false.

**Review by banatt — APPROVED** [review]
lgtm!

**Review by niqniqniqq — APPROVED** [review]

**Review by kei-gnu — APPROVED** [review]
LGTM!

**Comment by R-HNF** [comment]
@banatt @niqniqniqq @kei-gnu 
Thank you for your review! I'll merge it!
